// data/mockData.ts
import { Service, Product } from '../../../types/service.types';

export const services: Service[] = [
  {
    id: '1',
    name: 'Painting',
    slug: 'painting',
    description: 'Professional painting services for homes and offices',
    subCategories: [
      { id: 'p1', name: 'Interior Painting', slug: 'interior-painting', serviceId: '1' },
      { id: 'p2', name: 'Exterior Painting', slug: 'exterior-painting', serviceId: '1' },
      { id: 'p3', name: 'Wallpaper Installation', slug: 'wallpaper', serviceId: '1' },
      { id: 'p4', name: 'Decorative Painting', slug: 'decorative', serviceId: '1' },
    ],
  },
  {
    id: '2',
    name: 'Cleaning',
    slug: 'cleaning',
    description: 'Thorough cleaning services for residential and commercial spaces',
    subCategories: [
      { id: 'c1', name: 'Deep Cleaning', slug: 'deep-cleaning', serviceId: '2' },
      { id: 'c2', name: 'Regular Cleaning', slug: 'regular-cleaning', serviceId: '2' },
      { id: 'c3', name: 'Move In/Out Cleaning', slug: 'move-cleaning', serviceId: '2' },
      { id: 'c4', name: 'Office Cleaning', slug: 'office-cleaning', serviceId: '2' },
    ],
  },
  {
    id: '3',
    name: 'Furniture',
    slug: 'furniture',
    description: 'Furniture assembly, repair, and installation',
    subCategories: [
      { id: 'f1', name: 'Assembly', slug: 'assembly', serviceId: '3' },
      { id: 'f2', name: 'Repair', slug: 'repair', serviceId: '3' },
      { id: 'f3', name: 'Installation', slug: 'installation', serviceId: '3' },
      { id: 'f4', name: 'Upholstery', slug: 'upholstery', serviceId: '3' },
    ],
  },
  {
    id: '4',
    name: 'Plumbing',
    slug: 'plumbing',
    description: 'Professional plumbing services and repairs',
    subCategories: [
      { id: 'pl1', name: 'Leak Repair', slug: 'leak-repair', serviceId: '4' },
      { id: 'pl2', name: 'Installation', slug: 'plumbing-installation', serviceId: '4' },
      { id: 'pl3', name: 'Drain Cleaning', slug: 'drain-cleaning', serviceId: '4' },
      { id: 'pl4', name: 'Water Heater', slug: 'water-heater', serviceId: '4' },
    ],
  },
];

export const products: Product[] = [
  // Painting products
  {
    id: 'p1',
    name: 'Interior Room Painting',
    description: 'Professional painting for a single room including walls and trim',
    price: 299,
    serviceId: '1',
    subCategoryId: 'p1',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400',
    rating: 4.8,
    reviews: 124,
    duration: '1 day',
    popular: true,
    featured: true,
  },
  {
    id: 'p2',
    name: 'Exterior House Painting',
    description: 'Complete exterior painting service with weather-resistant paint',
    price: 1999,
    serviceId: '1',
    subCategoryId: 'p2',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w-400',
    rating: 4.7,
    reviews: 89,
    duration: '3-5 days',
    popular: true,
    featured: false,
  },
  {
    id: 'p3',
    name: 'Wallpaper Installation',
    description: 'Professional wallpaper installation for feature walls',
    price: 499,
    serviceId: '1',
    subCategoryId: 'p3',
    image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400',
    rating: 4.6,
    reviews: 67,
    duration: '2 days',
    popular: false,
    featured: true,
  },
  
  // Cleaning products
  {
    id: 'c1',
    name: 'Deep Cleaning Package',
    description: 'Complete deep cleaning for 2-bedroom apartments',
    price: 199,
    serviceId: '2',
    subCategoryId: 'c1',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
    rating: 4.9,
    reviews: 256,
    duration: '4 hours',
    popular: true,
    featured: true,
  },
  {
    id: 'c2',
    name: 'Regular Maintenance Cleaning',
    description: 'Weekly or bi-weekly cleaning service',
    price: 129,
    serviceId: '2',
    subCategoryId: 'c2',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    rating: 4.7,
    reviews: 178,
    duration: '2 hours',
    popular: true,
    featured: false,
  },
  
  // Furniture products
  {
    id: 'f1',
    name: 'Furniture Assembly Service',
    description: 'Professional assembly of flat-pack furniture',
    price: 99,
    serviceId: '3',
    subCategoryId: 'f1',
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=400',
    rating: 4.8,
    reviews: 145,
    duration: '2 hours',
    popular: true,
    featured: true,
  },
  {
    id: 'f2',
    name: 'Furniture Repair',
    description: 'Repair and restoration of damaged furniture',
    price: 149,
    serviceId: '3',
    subCategoryId: 'f2',
    image: 'https://images.unsplash.com/photo-1595429035836-c1e7d019f6c3?w=400',
    rating: 4.6,
    reviews: 92,
    duration: '3-4 hours',
    popular: false,
    featured: true,
  },
  
  // Plumbing products
  {
    id: 'pl1',
    name: 'Leak Detection & Repair',
    description: 'Professional leak detection and repair service',
    price: 149,
    serviceId: '4',
    subCategoryId: 'pl1',
    image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400',
    rating: 4.7,
    reviews: 134,
    duration: '2-3 hours',
    popular: true,
    featured: false,
  },
  // Add more products as needed...
];